name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.32.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
